site:
  title: Documentation
  start_page: home::index.adoc
  url: http:localhost:5000
content:
  branches: [v*]
  sources: 
  - url: .
    start_path: home
    branches: HEAD
  - url: https://github.com/JakeSCahill/hazelcast-reference-manual #../hazelcast-reference-manual 
    start_path: docs
    #branches: HEAD
ui: 
  bundle:
    url: ../docs-poc-ui/build/ui-bundle.zip #https://github.com/JakeSCahill/docs-poc-ui/releases/download/v1.1.8/ui-bundle.zip #../docs-poc-ui/build/ui-bundle.zip
    snapshot: true
  #supplemental_files: ./supplemental_ui 
asciidoc:
  attributes:
    page-pagination: true
    page-survey: https://www.surveymonkey.co.uk/r/NYGJNF9
    idprefix: ''
    idseparator: '-'
    imdg-javadoc: https://docs.hazelcast.org/docs/latest-dev/javadoc
    imdg-samples: https://github.com/hazelcast/hazelcast-code-samples
    imdg-core: https://github.com/hazelcast/hazelcast/tree/master/hazelcast/src/main/java/com/hazelcast
    hz-refman: https://docs.hazelcast.org/docs/latest/manual/html-single/index.html
    jet-refman: https://docs.hazelcast.org/docs/jet/latest/manual/
    docs-archive: 'https://hazelcast.org/imdg/download/archives/'
  extensions:
    - ./lib/tabs-block.js
