# This workflow will take the contents of the develop branch and build a documentation site in the docs folder.

name: Build site

on:
  push:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 10
    - run: |
        git config --global user.name 'JakeSCahill'
        git config --global user.email '45230295+JakeSCahill@users.noreply.github.com'
        npm i
        npm run-script build
        touch docs/.nojekyll
        git add -f docs
        git commit -m "Deploy site"
        git push origin HEAD:develop
